plugins {
    id 'fabric-loom'
}

base {
    archivesName = "${mod_id}-fabric"
}

sourceSets {
    main {
        java.srcDir('../common/src/main/java')
        resources.srcDir('../common/src/main/resources')
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
    withSourcesJar()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            runDir('runs/server')
        }
    }
}

processResources {
    def properties = [
        version: "${mod_version}+${minecraft_version}",
        mod_id: mod_id,
        mod_name: mod_name,
        mod_description: mod_description,
        mod_authors: mod_authors,
        mod_license: mod_license,
        minecraft_version: minecraft_version,
        java_version: java_version,
        fabric_loader_version: fabric_loader_version
    ]
    inputs.properties(properties)
    filesMatching('fabric.mod.json') {
        expand(properties)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = java_version as int
}
